optimize predict logic
imgcook/pipcook-plugin-detection-fasterrcnn-model pull request #1
Opened 2020-08-18 11:00 UTC by rickycao-qy

1 As requested by @lewis617, the model should return label names with classes
2. predict should return numbers not strings

2020-08-25 14:12 UTC, FeelyChau requested changes

2020-08-25 14:12 UTC, FeelyChau commented on src/index.ts
> +    log = JSON.parse(fs.readFileSync(path.join(recoverPath, '..', 'metadata.json'), 'utf8'));
We could use `fs.readJson` instead.

2020-08-28 08:09 UTC, yorkie approved these changes, later dismissed

2020-09-02 10:06 UTC, yorkie approved these changes

2020-09-03 11:42 UTC, FeelyChau approved these changes

2020-09-03 12:15 UTC, merged